# Generated by Django 3.2.8 on 2021-10-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20211027_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_check',
            name='org_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_check',
            name='usr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
